### PR TITLE
Files for uploading to PyPI

### PR DESCRIPTION
**Pull request by cbrnr**
This is taken from scot - I'm testing it on TestPyPI in a minute, and if this works we're good to go.

### CODE REVIEW

**Comment by cbrnr** [comment]
OK, it's not that simple. The distribution is too large to upload to PyPI. We should think about other ways of getting this example data.

**Comment by mbillingr** [comment]
Maybe we could at a function to scot that downloads it directly from github?
MNE has very sophisticated example download mechanisms. maybe they can give us an idea.

An alternative could be to upload the data to a place like [zendoo](https://zenodo.org/) if they allow anonymous downloads.

**Comment by cbrnr** [comment]
Downloading from GitHub sounds good to me. I'll check out how this can be implemented.

**Comment by cbrnr** [comment]
It's on [TestPyPI](https://testpypi.python.org/pypi/scot-data) - could you please test if the downloading mechanism is working?

**Comment by cbrnr** [comment]
I just tested it, it is working. However, it downloads the file into the site-packages/scotdata folder, and I don't know if this is a good idea (for example, users need to have write access to this folder and I'm not sure this is the case).

Also, `pip uninstall scot-data` does not remove the downloaded file (of course, because it is not part of the package, but I don't like this file lying around inside site-packages). I think MNE has the same approach, but they download their sample data to site-packages/examples.

Any ideas how to improve this?

**Comment by mbillingr** [comment]
By default I would put the downloads somewhere in the user's home directory. Alternatively, if we do not want to arbitrarily mess up the user file system, we could force the user to specify a storage location when accessing the example data.

Also, I think it would be convenient to put the code for downloading data in the scot repository. That way we avoid multiple packages.

**Comment by cbrnr** [comment]
+1 for merging scot-data into scot.

What if we write a function to get the sample data, which has the file location as an argument (by default this could be the working directory)? Then this function must be called in all example scripts.

**Comment by mbillingr** [comment]
+1 for the function.

I don't the working directory is a good default. 
This could lead to multiple downloads of the example data in different locations, which would be especially annoying if the user starts installed exapmles and does not expect them to mess with the current directory.

**Comment by mbillingr** [comment]
Let's continue the discussion over at scot.

**Pull request closed without merging**
